baseurl = "https://jordansjourney.com/"
title = "Jordan's Journey"
author = "Larry Vincent	"
paginate = 5
theme = "blank"

[params]
    description = "The story of Jordan Vincent, cancer slayer."
    dateFormatToUse = "2006-01-02"
	mainSections = ['post']
	lv_stat = 1

[menu]
[[menu.main]]
  identifier = "about"
  name = "About"
  url = "/about/"
  weight = 1
[[menu.main]]
  identifier = "journey"
  name = "The Journey"
  url = "/post/"
  weight = 1